apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: portfolio-k8s
  labels:
    app: backend
    project: kubernetes-deployment-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
        project: kubernetes-deployment-lab
    spec:
      containers:
        - name: backend
          image: ghcr.io/bleriotwafo/kubernetes-deployment-lab-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: backend-config
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health/live
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"